#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag "markusressel/telegram-click" "markusressel/telegram-click:${TRAVIS_TAG}"
docker push "markusressel/telegram-click:${TRAVIS_TAG}"