name: Docker Image Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # this writes the tag name into GIT_TAG_NAME
      - name: Get tag name
        uses: olegtarasov/get-tag@2.1.3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag markusressel/telegram-click:$GIT_TAG_NAME
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push the Docker image
        run: docker push markusressel/telegram-click:$GIT_TAG_NAME
